create extension if not exists pg_trgm with schema extensions;

create table if not exists public.meta (
    key text primary key,
    value text not null
);

create table if not exists public.workbooks (
    id bigint primary key generated by default as identity,
    workbook_path text not null,
    workbook_name text not null,
    created_at timestamptz not null default timezone('utc', now()),
    last_loaded_at timestamptz not null default timezone('utc', now()),
    last_synced_at timestamptz not null default timezone('utc', now()),
    record_count integer not null default 0,
    plantio_count integer not null default 0,
    source_mtime_ns bigint not null default 0,
    source_size bigint not null default 0
);

create unique index if not exists uq_workbooks_workbook_path_ci
    on public.workbooks (lower(workbook_path));

create table if not exists public.records (
    id bigint primary key generated by default as identity,
    workbook_id bigint not null references public.workbooks(id) on delete cascade,
    uid text not null,
    excel_row integer not null,
    oficio_processo text not null default '',
    eletronico text not null default '',
    caixa text not null default '',
    av_tec text not null default '',
    compensacao text not null default '',
    endereco text not null default '',
    microbacia text not null default '',
    compensado text not null default '',
    endereco_plantio text not null default '',
    latitude_plantio text not null default '',
    longitude_plantio text not null default '',
    latitude text not null default '',
    longitude text not null default '',
    synced_at timestamptz not null default timezone('utc', now()),
    oficio_year text not null default '',
    tipo_key text not null default '',
    microbacia_key text not null default '',
    search_blob_norm text not null default ''
);

create unique index if not exists uq_records_workbook_uid_ci
    on public.records (workbook_id, lower(uid));

create unique index if not exists uq_records_workbook_row
    on public.records (workbook_id, excel_row);

create index if not exists idx_records_workbook_av_tec
    on public.records (workbook_id, av_tec);

create index if not exists idx_records_workbook_micro_key
    on public.records (workbook_id, microbacia_key);

create index if not exists idx_records_workbook_tipo_key
    on public.records (workbook_id, tipo_key);

create index if not exists idx_records_workbook_year
    on public.records (workbook_id, oficio_year);

create index if not exists idx_records_search_blob_norm_trgm
    on public.records using gin (search_blob_norm gin_trgm_ops);

create table if not exists public.plantios (
    id bigint primary key generated by default as identity,
    record_id bigint not null references public.records(id) on delete cascade,
    sequence integer not null,
    endereco text not null default '',
    qtd_mudas text not null default '',
    latitude text not null default '',
    longitude text not null default ''
);

create unique index if not exists uq_plantios_record_sequence
    on public.plantios (record_id, sequence);

create table if not exists public.audit_events (
    id bigint primary key generated by default as identity,
    event_id text not null,
    workbook_id bigint references public.workbooks(id) on delete set null,
    workbook_path text not null,
    timestamp timestamptz not null,
    action text not null,
    summary text not null,
    backup_path text not null default '',
    metadata_json jsonb not null default '{}'::jsonb,
    before_json jsonb,
    after_json jsonb,
    mirrored_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_audit_events_event_id
    on public.audit_events (event_id);

create index if not exists idx_audit_events_workbook_timestamp
    on public.audit_events (workbook_id, timestamp desc);

create table if not exists public.tcras (
    uid text primary key,
    numero_processo text not null default '',
    numero_tcra text not null default '',
    local text not null default '',
    endereco text not null default '',
    bairro text not null default '',
    orgao_acompanhamento text not null default '',
    status text not null default '',
    data_assinatura date,
    prazo_final date,
    periodicidade_relatorio_meses integer,
    data_ultimo_relatorio date,
    data_proximo_relatorio date,
    area_m2 double precision,
    numero_mudas_previsto integer,
    servicos_exigidos text not null default '',
    responsavel_execucao text not null default '',
    observacoes text not null default '',
    mpsp_relacionado text not null default '',
    inquerito_civil text not null default '',
    search_blob_norm text not null default '',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists idx_tcras_numero_processo
    on public.tcras (lower(numero_processo));

create index if not exists idx_tcras_numero_tcra
    on public.tcras (lower(numero_tcra));

create index if not exists idx_tcras_prazo_final
    on public.tcras (prazo_final);

create index if not exists idx_tcras_status
    on public.tcras (lower(status));

create index if not exists idx_tcras_search_blob_norm_trgm
    on public.tcras using gin (search_blob_norm gin_trgm_ops);

create table if not exists public.tcra_eventos (
    id bigint primary key generated by default as identity,
    tcra_uid text not null references public.tcras(uid) on delete cascade,
    sequence integer not null,
    data_evento date,
    tipo_evento text not null default '',
    descricao text not null default '',
    prazo_resultante date,
    status_resultante text not null default '',
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists uq_tcra_eventos_uid_sequence
    on public.tcra_eventos (tcra_uid, sequence);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

drop trigger if exists trg_tcras_touch_updated_at on public.tcras;
create trigger trg_tcras_touch_updated_at
before update on public.tcras
for each row
execute function public.touch_updated_at();

drop trigger if exists trg_tcra_eventos_touch_updated_at on public.tcra_eventos;
create trigger trg_tcra_eventos_touch_updated_at
before update on public.tcra_eventos
for each row
execute function public.touch_updated_at();

alter table public.meta enable row level security;
alter table public.workbooks enable row level security;
alter table public.records enable row level security;
alter table public.plantios enable row level security;
alter table public.audit_events enable row level security;
alter table public.tcras enable row level security;
alter table public.tcra_eventos enable row level security;
